service:
  name: cucumber-chrome-aws

provider:
  name: aws
  runtime: java8
  region: ${opt:region}
  iamRoleStatements:
  - Effect: Allow
    Resource: "*"
    Action:
    - ses:SendEmail
  - Effect: Allow
    Resource: arn:aws:s3:::cucumber-html-report-files/*
    Action:
    - s3:PutObject

package:
  artifact: target/webdrivertraining.1.0-SNAPSHOT.jar

functions:
  runCucumber:
    handler: com.octopus.LambdaEntry::runCucumber
    timeout: 300
    memorySize: 512
    events:
    - http:
        method: post
        path: runCucumber
        integration: lambda
        request:
          parameters:
            headers:
              'X-Amz-Invocation-Type': true
          template:
            text/plain: >
              {
                "feature":"$util.escapeJavaScript($input.body).replaceAll("\\'","'")",
                "id": "$util.escapeJavaScript($input.params().header.get('Test-Id')).replaceAll("\\'","'")",
                "headers": {
                  #foreach($param in $input.params().header.keySet())
                  "$param": "$util.escapeJavaScript($input.params().header.get($param))" #if($foreach.hasNext),#end
                  #end
                }
              }
        response:
          headers:
            Content-Type: "'application/json'"
          template: $util.parseJson($input.body)