name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Reattach HEAD
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/webdriver:$(cat /home/runner/work/WebDriverTraining/WebDriverTraining/version.txt)
        docker tag ${{ secrets.DOCKER_USERNAME }}/webdriver:$(cat /home/runner/work/WebDriverTraining/WebDriverTraining/version.txt) ${{ secrets.DOCKER_USERNAME }}/webdriver:latest
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: |
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/webdriver:$(cat /home/runner/work/WebDriverTraining/WebDriverTraining/version.txt)
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/webdriver:latest
